server:
  port: 8080

spring:
  application:
    name: iot-api

  datasource:
    url: jdbc:mysql://localhost:3306/iot_charge_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

logging:
  level:
    com.iot: DEBUG           # 项目自身日志
    io.netty: INFO            # Netty 保持 INFO

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.iot.core.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# RocketMQ 配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: iot-charge-producer

# JWT 配置
jwt:
  secret: iot-charge-platform-secret-keyiot-charge-platform-secret-key
  expiration: 86400000

# MQTT Server 配置
mqtt:
  server:
    port: 1883 # MQTT 监听端口
    boss-thread-count: 2 # Boss 线程数（接收连接）
    worker-thread-count: 8 # Worker 线程数（处理 I/O）
    idle-read-timeout-seconds: 90 # 读空闲超时（秒）
    so-backlog: 1024 # 连接等待队列长度
    max-connections: 2 # 最大连接数
    # 直接内存保护
    memory-protect:
      high-watermark: 0.9 # 暂停 autoRead 阈值
      low-watermark: 0.6 # 恢复 autoRead 阈值
      check-interval-cron: "*/10 * * * * *" # 检查间隔（cron 表达式）
